#! /bin/bash -e
# VERBOSE=1 LOCK=/run/xtables.lock iptables-tracing icmp and dst host 1.1.1.1

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${GREEN}You may want to run \"sysctl -w net.netfilter.nf_log_all_netns=1\" to log all netns${NC}"

if [[ -z "$LOCK" ]]; then
    LOCK=/run/xtables.lock
fi
exec 4<>$LOCK
echo -e "${GREEN}Use flock: ${LOCK}${NC}"

iptables="${0%-tracing}"
export iptables

bpf_bytecode=$(eval "nfbpf_compile RAW '$@'")

function foreach_chain() {
    action=$1
    for table in $($iptables-save | grep '^\*'); do
        table=${table##\*}
        for chain in $($iptables-save -t $table | awk '$1 ~ /^:/ {print $1}'); do
            chain=${chain##:}
            count=$($iptables-save -t $table | grep -c -- "-A $chain\s" || true)
            [[ "$count" == 0 ]] && continue
            $action $table $chain
        done
    done
}

function clear_log() {
    table=$1
    chain=$2

    declare -A rules
    idx=0
    while IFS= read -r line; do
        idx=$((idx+1))
        if [[ -z ${rules["$line"]} ]]; then
            rules["$line"]="$idx"
        else
            rules["$line"]="$idx,${rules["$line"]}"
        fi
    done < <($iptables-save -t $table | grep -- "-A $chain\s")

    while IFS= read -r line; do
        for idx in ${rules["$line"]//,/ }; do
            [[ -n "$VERBOSE" ]] && echo $iptables -t $table -D $chain $idx
            $iptables -t $table -D $chain $idx
        done
        rules["$line"]=""
    done < <($iptables-save -t $table | tac | grep -- "-A $chain\s.*$bpf_bytecode")
}

function insert_log() {
    table=$1
    chain=$2

    idx=1
    while IFS= read -r line; do
        line=${line%% -j *}
        line=${line%% -g *}
        line=${line#-A $chain } # would fail for bare '-A INPUT'
        line=${line#-A $chain} # doesn't have side effect if the previous one succeeds
        insert_idx=$((idx*2-1))
        [[ -n "$VERBOSE" ]] && echo $iptables -t $table -I $chain $insert_idx -m bpf --bytecode \"$bpf_bytecode\" $line -j LOG --log-prefix \"$insert_idx/$table/$chain\"
        eval $iptables -t $table -I $chain $insert_idx -m bpf --bytecode \"$bpf_bytecode\" $line -j LOG --log-prefix \"$insert_idx/$table/$chain\"
        ((idx++))
    done < <($iptables-save -t $table | grep -- "^-A $chain\s")
}


function on_exit() {
    echo "Clearing log rules"
    foreach_chain clear_log
    echo "$($iptables-save | grep -Pc '^-A' || true) rules after tracing"
    flock -u 4
}
trap on_exit EXIT

flock -x 4
echo "$($iptables-save | grep -Pc '^-A' || true) rules before tracing"
foreach_chain insert_log

echo "tail -f /var/log/syslog"
while read line; do
    hit=$(echo $line | grep -Po '(?<= )[-\w]+/[-\w]+/[-\w]+?(?=IN=)' || true)
    [[ -z "$hit" ]] && continue
    IFS=/ read idx table chain <<<"$hit"
    echo "chain: $chain, table: $table, idx: $idx"
    chain=$($iptables-save -t $table | grep -Po "(?<=-A )$chain\S*" | sort -u)
    rule=$($iptables -t $table -L $chain $((idx+1)) | tr -s ' ')
    skb=$(echo $line | grep -Po 'IN=.*')
    echo -e "${RED}$rule${NC} hit by $skb"
done < <(tail -f /var/log/syslog) || true
